### ISSUE TITLE
kudos v2 - kudos can imbue special powers for their owners

### ISSUE THREAD

**Issue by owocki** [mbeacom/gitcoin-erc721#146]
some ideas to test:

- we charge people for bounties, but if they own a kudos with a 'free bounties' effect, they don't get charged anymore.
- a kudos that grants special attributes to someone's avatar in the avatar builder
- a 'gitcoin verified' kudos that shows off that we've vetted a funder, on their profile

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2621
