### ISSUE TITLE
the big production deploy ticket

### ISSUE THREAD

**Issue by owocki** [mbeacom/gitcoin-erc721#182]
1. mint all tokens in kudos.yaml that aren't in kudos_mainnet.yaml to 0x56c72cda0b04fc39a25d0b6a64fa258fad46d664 mainnet contract. MAKE SURE THE tokenURI info is correct first!!
2. set the tokenURI's of all the kudos_status.yaml tokens to point to gitcoin.co instead of kudosdemo.gitcoin.co [reference slack convo](https://gitcoincore.slack.com/archives/CAXCZR8K0/p1539570122000100)
3. deploy `kudos-v1` branch to master, then deploy to prod
4. test end to end 
5. anything else?

**Comment by octavioamu** [comment]
This issue was moved to gitcoinco/web#2605
